version: '3.8'

services:
  form-monitoreo:
    container_name: Form-Monitoreo
    image: slotyholly/form-monitoreo:latest
    volumes:
      - sqlite_data:/app/instance
    environment:
      - FLASK_APP=/run.py
      - FLASK_ENV=production
      - SECRET_KEY=nyrmcwznsrQHzCkTCdpPFzUubqZQBa
      - ENVIRONMENT=docker
    command: gunicorn -w 4 -b 0.0.0.0:5000 run:app
    restart: always

  nginx:
    image: slotyholly/form-monitoreo-nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "5000:443"
    depends_on:
      - form-monitoreo

volumes:
  sqlite_data:
    driver: local