version: '3.8'

services:
  form-monitoreo:
    container_name: Form-Monitoreo
    image: slotyholly/form-monitoreo:latest
    ports:
      - "5000:5000"
    volumes:
      - sqlite_data:/app/instance
    environment:
      - FLASK_APP=/run.py
      - FLASK_ENV=production
      - SECRET_KEY=nyrmcwznsrQHzCkTCdpPFzUubqZQBa
    command: gunicorn -w 4 -b 0.0.0.0:5000 run:app
    restart: always

volumes:
  sqlite_data:
    driver: local