version: '3.8'

services:
  form-monitoreo:
    container_name: Form-Monitoreo
    image: slotyholly/form-monitoreo:latest
    ports:
      - "5000:5000"
    volumes:
      - sqlite_data:/app/instance
    environment:
      - FLASK_APP=/run.py
      - FLASK_ENV=production
      - SECRET_KEY=nyrmcwznsrQHzCkTCdpPFzUubqZQBa
    command: python3 /run.py
    restart: always

volumes:
  sqlite_data:
    driver: local