version: '3.8'

services:
  form-monitoreo:
    container_name: Form-Monitoreo
    image: slotyholly/form-monitoreo:latest
    volumes:
      - sqlite_data:/app/instance
    environment:
      - FLASK_APP=/run.py
      - FLASK_ENV=production
      - SECRET_KEY=nyrmcwznsrQHzCkTCdpPFzUubqZQBa
    command: gunicorn -w 4 -b 0.0.0.0:5000 run:app
    restart: always

  nginx:
    image: nginx:stable
    container_name: nginx-proxy
    ports:
      - "5000:443"
    volumes:
      - ./app/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app/nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - form-monitoreo

volumes:
  sqlite_data:
    driver: local