version: '3.8'

services:
  app:
    container_name: Form-Monitoreo
    image: slotyholly/form-monitoreo:latest
    build: .  # Solo si quieres construir la imagen localmente
    ports:
      - "5000:5000"
    volumes:
      - sqlite_data:/app/instance  # Volumen para persistencia de SQLite
    environment:
      - FLASK_APP=/run.py
      - FLASK_ENV=production
      - SECRET_KEY=nyrmcwznsrQHzCkTCdpPFzUubqZQBa
    command: python3 /run.py  # Asegura que ejecuta el archivo correcto
    restart: always

  watchtower:
    container_name: Watchtower
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 3600 Form-Monitoreo  # Solo monitorea `Form-Monitoreo`

volumes:
  sqlite_data:
    driver: local
